#!/usr/bin/env bash
# Assemble the single-app demo gallery for Fly.io (ADR-0023) into build/.
#
# One Docker image serves every demo behind a sub-path (gallery_app.py mounts each
# example's indah app under /<slug> and a gallery index at /). Copies gallery_app.py
# + the demo example files + writes the Dockerfile/requirements/fly.toml. Does NOT
# deploy (see deploy_fly.sh / README.md).
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
out="$here/build"
app="${FLY_APP:-indah-demos}"
region="${FLY_REGION:-sin}"

# Example modules the gallery mounts (must match MANIFEST in gallery_app.py).
examples=(chatbot training_dashboard diffusion poster upload_classify object_detection charts stocks prettymap map_poster grc_map audio_analysis)

# Install the published wheel from PyPI (the python:3.12-slim base has no git, and a
# PyPI install is what a user would run). Bump this when the gallery should track a new
# release; the demos themselves are copied into the image, not pulled from the package.
INDAH_REQ='indah>=0.2.1'

rm -rf "$out"
mkdir -p "$out"
cp "$here/gallery_app.py" "$out/"
cp "$here/landing.html" "$out/"   # the landing-page template gallery_app.py reads
cp -r "$here/thumbnails" "$out/"  # real per-demo screenshots for the gallery cards
for mod in "${examples[@]}"; do
  cp "$repo/examples/$mod.py" "$out/$mod.py"
done

{
  echo "$INDAH_REQ"
  echo "uvicorn[standard]"
  echo "matplotlib"          # charts.py uses it (duck-typed); the rest need only indah
  echo "onnxruntime"         # upload_classify.py's real MobileNetV2 classifier (CPU)
  echo "pillow"              # upload_classify.py's image decode/resize
  echo "huggingface_hub"     # upload_classify.py: download + cache the ONNX weights
  echo "numpy"               # audio_analysis.py: waveform synthesis + numpy.fft spectrogram
} > "$out/requirements.txt"

cat > "$out/Dockerfile" <<'DOCKER'
FROM python:3.12-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 7860
# One app mounts every demo under /<slug>; --factory builds it (imports the examples).
CMD ["uvicorn", "gallery_app:create_gallery", "--factory", "--host", "0.0.0.0", "--port", "7860"]
DOCKER

cat > "$out/fly.toml" <<TOML
# Generated by deploy/fly/build_gallery.sh - do not edit by hand.
app = "$app"
primary_region = "$region"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  # Bound simultaneous SSE connections on this one machine (deploy_fly.sh runs with
  # --ha=false, so Fly never provisions a second machine under load - this is what
  # keeps a connection flood from OOMing the box instead). ADR-0024.
  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
TOML

echo "built $out/ (app=$app, region=$region, ${#examples[@]} demos)"
