#!/usr/bin/env bash
# Deploy the indah demos to Fly.io - one app per demo (ADR-0023, self-hosted path).
#
# Reuses the Docker build folders from deploy/spaces/build/<slug>/ (run
# ../spaces/build_space.sh first). For each demo it writes a fly.toml into the build
# folder and `fly deploy`s it. Machines auto-stop when idle (min 0), so idle demos
# cost ~nothing.
#
# Prereqs: flyctl installed (https://fly.io/docs/flyctl/install/) and `fly auth login`.
# Usage:
#   ../spaces/build_space.sh
#   ./deploy_fly.sh              # all demos
#   ./deploy_fly.sh poster       # one, by slug
# Env:
#   FLY_PREFIX  app-name prefix (default "indah-demo"; Fly app names are GLOBAL, so
#               change this if a name is taken), FLY_REGION (default "sin").
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
build="$(cd "$here/../spaces" && pwd)/build"
manifest="$(cd "$here/../spaces" && pwd)/demos.tsv"
prefix="${FLY_PREFIX:-indah-demo}"
region="${FLY_REGION:-sin}"
only="${1:-}"

command -v fly >/dev/null 2>&1 || { echo "flyctl not found - install it and 'fly auth login' first." >&2; exit 1; }

while IFS=$'\t' read -r slug example title emoji extra; do
  case "$slug" in ''|\#*) continue ;; esac
  [ -n "$only" ] && [ "$slug" != "$only" ] && continue
  dir="$build/$slug"
  [ -d "$dir" ] || { echo "!! $slug: $dir missing (run ../spaces/build_space.sh), skipping" >&2; continue; }
  app="$prefix-$slug"

  cat > "$dir/fly.toml" <<TOML
# Generated by deploy/fly/deploy_fly.sh - do not edit by hand.
app = "$app"
primary_region = "$region"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
TOML

  echo ">> $app  ($title)"
  fly apps create "$app" >/dev/null 2>&1 || true   # idempotent: ignore "already exists"
  fly deploy "$dir" --config "$dir/fly.toml" --ha=false
  echo "   live at https://$app.fly.dev"
done < "$manifest"

echo
echo "Done. Add each https://$prefix-<slug>.fly.dev URL to website/docs/gallery.md."
