"""One ASGI app that hosts every indah demo behind sub-paths (ADR-0023, Fly.io).

A single Starlette app mounts each demo's indah app under `/<slug>` and serves a
gallery index at `/`. This works because the indah shell uses document-relative URLs
(`api/stream`, `api/event`, ...) so it survives a base path - the same property that
makes it run behind Colab's and Runpod's proxies (ADR-0001). One machine, one domain
(`.../poster`, `.../chatbot`, ...), and it dogfoods indah's single-port/base-path
design.

Run in the deploy image with uvicorn's factory mode:
    uvicorn gallery_app:create_gallery --factory --host 0.0.0.0 --port 7860

`build_gallery` is pure (imports only Starlette) so it is unit-testable without the
examples; `create_gallery` imports the example modules (present in the deploy image).
"""

from __future__ import annotations

import base64
import html
import importlib
import time
from pathlib import Path
from typing import Any

from starlette.applications import Starlette
from starlette.responses import HTMLResponse, PlainTextResponse
from starlette.routing import Mount, Route
from starlette.staticfiles import StaticFiles
from starlette.types import ASGIApp, Receive, Scope, Send

from indah.session_store import InMemorySessionStore

# Real per-demo screenshots (generated by scripts/capture_thumbnails.py) used as the
# gallery card thumbnails; a demo with no PNG here falls back to a gradient tile.
THUMB_DIR = Path(__file__).parent / "thumbnails"

# slug (URL + Fly), title, emoji, example module name (copied flat into the image).
MANIFEST: list[tuple[str, str, str, str]] = [
    ("chatbot", "Streaming chatbot", "💬", "chatbot"),
    ("training-dashboard", "Live training dashboard", "📈", "training_dashboard"),
    ("diffusion", "Image generation", "🎨", "diffusion"),
    ("poster", "Poster generator", "🖼️", "poster"),
    ("image-classify", "Image classifier", "🔍", "upload_classify"),
    ("object-detection", "Object detection", "🎯", "object_detection"),
    ("charts", "Hybrid charting", "📊", "charts"),
    ("stocks", "Stock peer analysis", "💹", "stocks"),
    ("prettymap", "Pretty map", "🗺️", "prettymap"),
    ("map-poster", "Map poster", "🗾", "map_poster"),
    ("grc-map", "GRC map", "🇸🇬", "grc_map"),
    ("audio-analysis", "Audio analysis", "🎧", "audio_analysis"),
    ("gpx-viewer", "GPX viewer", "🥾", "gpx_viewer"),
]

# One-line blurb per demo for the gallery cards (keyed by slug).
BLURBS: dict[str, str] = {
    "chatbot": "Chat replies streamed token by token into role bubbles.",
    "training-dashboard": "Loss curves and live KPI cards while a model trains.",
    "diffusion": "A prompt-to-image sampler refining from noise, with live progress.",
    "poster": "Tweak controls, watch a poster re-render live, then download it.",
    "image-classify": "Pick a sample photo or upload your own, and see the top predictions.",
    "object-detection": "Upload an image; hover a box to read what a mock detector found.",
    "charts": "An interactive client chart beside a server plot and a heatmap.",
    "stocks": "Pick peers and a horizon; see who's beating the group average.",
    "prettymap": "Restyle a generated city map and download it as SVG.",
    "map-poster": "A real OpenStreetMap neighborhood, restyled as a poster.",
    "grc-map": "Singapore's electoral divisions, shaded by electorate, over 4 elections.",
    "audio-analysis": "Synthesized vowels and instrument notes, streamed into a live spectrogram.",
    "gpx-viewer": "Scrub a real hiking trail; the map marker and elevation profile move together.",
}

# The Bunga mark (two magenta petals, two teal), inlined so the gallery needs no assets.
_BUNGA = (
    '<path d="M16 16C11.7 12.4 11.7 6 16 3.6C20.3 6 20.3 12.4 16 16Z" fill="#b5296b"/>'
    '<path d="M16 16C20.3 19.6 20.3 26 16 28.4C11.7 26 11.7 19.6 16 16Z" fill="#b5296b"/>'
    '<path d="M16 16C12.4 20.3 6 20.3 3.6 16C6 11.7 12.4 11.7 16 16Z" fill="#2e6d62"/>'
    '<path d="M16 16C19.6 20.3 26 20.3 28.4 16C26 11.7 19.6 11.7 16 16Z" fill="#2e6d62"/>'
)
_FAVICON_SVG = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">{_BUNGA}</svg>'
_FAVICON_URI = "data:image/svg+xml;base64," + base64.b64encode(_FAVICON_SVG.encode()).decode()
GITHUB_URL = "https://github.com/leejianrong/indah"
DOCS_URL = "https://indah.abangai.dev/docs/"


def _mark(size: int) -> str:
    return (
        f'<svg class="mark" width="{size}" height="{size}" viewBox="0 0 32 32" '
        f'role="img" aria-label="indah">{_BUNGA}</svg>'
    )


def _card(d: dict[str, Any]) -> str:
    slug = html.escape(d["slug"])
    title = html.escape(d["title"])
    blurb = html.escape(BLURBS.get(d["slug"], ""))
    if (THUMB_DIR / f"{d['slug']}.png").is_file():
        # A real screenshot (relative src, so it resolves under any base path).
        thumb = (
            f'<span class="thumb"><img class="thumb-img" src="thumbnails/{slug}.png" '
            f'alt="{title} preview" loading="lazy"></span>'
        )
    else:
        thumb = (
            '<span class="thumb"><span class="thumb-dots"></span>'
            f'<span class="thumb-emoji">{d["emoji"]}</span></span>'
        )
    # Relative link (trailing slash) so it resolves under any base path.
    return (
        f'<a class="card" href="{slug}/">{thumb}'
        f'<span class="card-body"><span class="card-title">{title}</span>'
        f'<span class="card-blurb">{blurb}</span></span></a>'
    )


# The comparison table lives on the landing page (not the docs). Framed to indah's
# strengths, but honest about what each row means.
_COMPARE = """
<tr><th scope="row">Reactive updates (no full-script rerun)</th>
  <td class="col-indah">Yes</td><td class="no">Reruns the script</td>
  <td class="mid">Event callbacks</td><td class="yes">Yes</td></tr>
<tr><th scope="row">No Node build at install or runtime</th>
  <td class="col-indah">Yes</td><td class="yes">Yes</td><td class="yes">Yes</td>
  <td class="no">Needs a Node build</td></tr>
<tr><th scope="row">Single port, notebook-proxy friendly</th>
  <td class="col-indah">Yes (SSE + POST)</td><td class="mid">WebSocket</td>
  <td class="mid">WebSocket</td><td class="mid">WebSocket</td></tr>
<tr><th scope="row">Token / point streaming built in</th>
  <td class="col-indah">Yes</td><td class="mid">Limited</td>
  <td class="yes">Yes</td><td class="mid">Limited</td></tr>
<tr><th scope="row">Runs inside a throwaway Colab / Runpod container</th>
  <td class="col-indah">Yes</td><td class="mid">Often</td>
  <td class="mid">Often</td><td class="no">Build step breaks</td></tr>
"""


_LANDING = (Path(__file__).parent / "landing.html").read_text(encoding="utf-8")


def _index_html(demos: list[dict[str, Any]]) -> str:
    cards = "".join(_card(d) for d in demos)
    return (
        _LANDING.replace("%%FAVICON%%", _FAVICON_URI)
        .replace("%%LOGO_NAV%%", _mark(26))
        .replace("%%LOGO_HERO%%", _mark(64))
        .replace("%%CARDS%%", cards)
        .replace("%%COMPARE%%", _COMPARE)
        .replace("%%GITHUB%%", GITHUB_URL)
        .replace("%%DOCS%%", DOCS_URL)
    )


_SECURITY_HEADERS = (
    (b"x-content-type-options", b"nosniff"),
    (b"referrer-policy", b"strict-origin-when-cross-origin"),
    (b"x-frame-options", b"DENY"),
)


class _SecurityHeadersMiddleware:
    """Baseline response headers for the public gallery (ADR-0024).

    Plain ASGI (not Starlette's ``BaseHTTPMiddleware``, which buffers/can misbehave on
    long-lived streaming responses) since this wraps the SSE stream endpoint too - it
    only needs to add a few headers to the outgoing ``http.response.start`` message.
    A full Content-Security-Policy is deferred until the bundled shell's asset/connect
    origins are audited - these three are safe defaults with no risk of breaking it.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        async def send_with_headers(message: Any) -> None:
            if message["type"] == "http.response.start":
                message["headers"] = list(message.get("headers", [])) + list(_SECURITY_HEADERS)
            await send(message)

        await self.app(scope, receive, send_with_headers)


class _RateLimitMiddleware:
    """Per-client-IP token bucket on the expensive routes (ADR-0024).

    Cloudflare (once wired, see the README) blocks abuse at the edge, before it
    reaches the box; this is the app-level backstop, since only the app understands
    indah's session/SSE semantics. Applied to every path ending in ``/api/event``,
    ``/api/upload``, or ``/api/stream`` (matches under any ``/<slug>`` mount). One
    process, one in-memory dict of buckets - no lock needed, same simplicity as
    ``InMemorySessionStore``.

    Client IP: ``Fly-Client-IP`` (set by Fly's edge) first, then the first
    ``X-Forwarded-For`` entry, then the raw socket peer.
    """

    _LIMITED_SUFFIXES = ("/api/event", "/api/upload", "/api/stream")

    def __init__(self, app: ASGIApp, *, capacity: int = 30, refill_per_second: float = 2.0) -> None:
        self.app = app
        self.capacity = capacity
        self.refill_per_second = refill_per_second
        self._buckets: dict[str, tuple[float, float]] = {}  # ip -> (tokens, last_refill)

    def _client_ip(self, scope: Scope) -> str:
        headers = dict(scope.get("headers") or [])
        fly_ip = headers.get(b"fly-client-ip")
        if fly_ip:
            return fly_ip.decode("latin-1")
        forwarded = headers.get(b"x-forwarded-for")
        if forwarded:
            return forwarded.decode("latin-1").split(",")[0].strip()
        client = scope.get("client")
        return client[0] if client else "unknown"

    def _allow(self, ip: str) -> bool:
        now = time.monotonic()
        tokens, last = self._buckets.get(ip, (float(self.capacity), now))
        tokens = min(self.capacity, tokens + (now - last) * self.refill_per_second)
        if tokens < 1:
            self._buckets[ip] = (tokens, now)
            return False
        self._buckets[ip] = (tokens - 1, now)
        return True

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http" or not scope["path"].endswith(self._LIMITED_SUFFIXES):
            await self.app(scope, receive, send)
            return
        if not self._allow(self._client_ip(scope)):
            response = PlainTextResponse("Too many requests.", status_code=429)
            await response(scope, receive, send)
            return
        await self.app(scope, receive, send)


def build_gallery(demos: list[dict[str, Any]]) -> ASGIApp:
    """Mount each demo app under `/<slug>` and serve a gallery index at `/`.

    ``demos`` is a list of ``{"slug","title","emoji","app"}`` (``app`` is an ASGI app).
    """

    async def index(_request):
        return HTMLResponse(_index_html(demos))

    routes: list[Any] = [Mount(f"/{d['slug']}", app=d["app"]) for d in demos]
    if THUMB_DIR.is_dir():
        routes.append(Mount("/thumbnails", app=StaticFiles(directory=THUMB_DIR)))
    routes.append(Route("/", index))
    app: ASGIApp = Starlette(routes=routes)
    return _SecurityHeadersMiddleware(_RateLimitMiddleware(app))


# The demo sources on GitHub, so each demo's "Source" link points at its own file.
SOURCE_BASE = "https://github.com/leejianrong/indah/blob/main/examples"

# Session bounds for the public deployment only (ADR-0024) - every other user of
# InMemorySessionStore (notebooks, tests) keeps the unbounded default.
_PUBLIC_MAX_SESSIONS = 200
_PUBLIC_SESSION_IDLE_TIMEOUT_SECONDS = 30 * 60


def apply_public_session_limits(app: ASGIApp) -> None:
    """Bound an example's session store for the public deployment (ADR-0024).

    A no-op for any store that isn't ``InMemorySessionStore`` (e.g. a future
    external backend, or an example built with ``session=`` instead of
    ``session_factory=``). Split out from ``create_gallery`` so it is
    unit-testable without importing every example's (sometimes heavy) deps.
    """
    store = app.state.store
    if isinstance(store, InMemorySessionStore):
        store.max_sessions = _PUBLIC_MAX_SESSIONS
        store.idle_timeout_seconds = _PUBLIC_SESSION_IDLE_TIMEOUT_SECONDS


def create_gallery() -> ASGIApp:
    """Import the example modules and build the gallery (used in the deploy image)."""
    demos = []
    for slug, title, emoji, module in MANIFEST:
        mod = importlib.import_module(module)
        # Per-demo page chrome (read by the shell's _index): a distinct tab title, a
        # clickable logo back to the gallery ("../" resolves from /<slug>/ to /), and a
        # link to this demo's source. The mounted sub-app carries its own app.state.
        mod.app.state.page_title = title
        mod.app.state.home_url = "../"
        mod.app.state.source_url = f"{SOURCE_BASE}/{module}.py"
        apply_public_session_limits(mod.app)
        demos.append({"slug": slug, "title": title, "emoji": emoji, "app": mod.app})
    return build_gallery(demos)
